### ISSUE TITLE
Create new club poster for the Fishbowl

### ISSUE THREAD

**Issue by mirdaki** [ufosc/club-documents#10]
From ACM: "The poster will be size 12x18 and shouldn't contain any time sensitive material (ie. "GBM coming up this Friday!", "We meet every Thursday from 2:00PM to 5:00PM", "Goals for this semester/things we did last semester"). The last stipulation is just because we can't speak for future ACM boards and while we would hope they continue to update the posters, we don't want the posters to contain inaccurate information should they choose not to."

What should we put on it?

**Comment by mirdaki** [comment]
It's due January 28th and needs to be a png file

**Comment by xeranimus** [comment]
Possible ideas:

Keep it consistent with the banner photos in club-assets. Match the background and font.

Include key points like:
"Creating, sharing, and promoting Open Source Software."
Possibly "Casual Codings, Tech Talks, and Codejams."

I am not sure what other SIGs are doing, but we should look to them.

**Comment by mirdaki** [comment]
Completed
