### ISSUE TITLE
Create amendment for USAB representative

### ISSUE THREAD

**Issue by mirdaki** [ufosc/club-documents#13]
The Undergraduate Student Advisory Board meets with the CS department to represent students interest, problems, research, etc. We need a representative to send and it feel we need a new officer position to handle it.

We need to get information from @JING1201 to put into writing what that all means and create a PR to add it to the constitutions

**Comment by hjarrell** [comment]
@xeranimus Close this when you create and merge the pull request

**Comment by hjarrell** [comment]
Closed by #31
