### ISSUE TITLE
Create a new singin url for 2019

### ISSUE THREAD

**Issue by mirdaki** [ufosc/club-documents#16]
This requires:
- [ ] A new Google form and sheet (can be copied from last years)
- [ ] Creating a new TinyURL that points to the sign in sheet with the address "tinyurl.com/ufosc19"
    - Note: You can share a form with some items pre-selected. Please select "no" to signing up for emails and/or sharing info with ACM and use the link that created for the TinyURL

**Comment by mirdaki** [comment]
We will hopefully get the club back end working sometime this semester to allow people to sign in on our website. So hopefully we wont need to do this much more.

**Comment by xeranimus** [comment]
https://tinyurl.com/ufosc19
