### ISSUE TITLE
Should we have an alumni channel or role?

### ISSUE THREAD

**Issue by mirdaki** [ufosc/club-documents#26]
What are people's thoughts on having an alumni channel/role? Someone who is an alumni may not want to get a whole lot of notifications about normal club chatter, but still be kept in the loop, so having a specific spot they could get check notifications for could keep them updated on club stuff. It would also give us a single spot to ask them for help (about an old project if they were a lead or if they could get their company to sponsor a meeting or do a workshop with us)

**Comment by hjarrell** [comment]
I created a channel and a role. Will need to add it to the bot to join the role.

**Comment by mirdaki** [comment]
OK cool!
