### ISSUE TITLE
Tasks to do before the end of the semester

### ISSUE THREAD

**Issue by mirdaki** [ufosc/club-documents#27]
Here is what I can think of, feel free to suggest more!

- [ ] T-shirt orders need to be taken and put through (#20)
- [x] Schedule and plan end of semester LAN party
- [ ] Get funding from ACM for another 12 months of the server and domain name
- [x] Recruit appointed officers
    - [x] Complete the USAB amendment (#13)
    - [ ] Find new project leads
- [x] Decide to be active over summer or not
- [x] Officer transition meeting (maybe?)
- [ ] Make and share "State of the Club" ([last years](https://github.com/ufosc/club-documents/blob/master/Semester-Notes/2018-Spring/State-of-the-Club.md))

**Comment by mirdaki** [comment]
Added tasks for making the "state of the club"

**Comment by mirdaki** [comment]
I've renewed the domain name for the next year (it expires on April 24th, 2020), but we will still need to get funding from ACM for the server costs (we still have a few months for that)

**Comment by hjarrell** [comment]
Closing this and using the individual issues instead, since the semester has ended.
