### ISSUE TITLE
Update Officer Duties

### ISSUE THREAD

**Issue by mirdaki** [ufosc/club-documents#28]
The new officer positions (Server Admin and USAB rep) need to be added to the [officer roles](https://github.com/ufosc/club-documents/blob/master/Administrative/Officer-Duties.md) so people can understand their responsibilities (useful for the officers as well as people wanting to run for a postion). 

It also might pay to make update the other ones to make sure things are still accurate.

**Comment by hjarrell** [comment]
Updated the duties for the new positions here: https://github.com/ufosc/club-documents/commit/41270a04916f6a11cf992d279e6b6dcceac5be4a
